### ISSUE TITLE
Timer length increases by double time spent in interfaces

### ISSUE THREAD

**Issue by HollandeP** [pieterjanbuntinx/kitten-tracker#43] opened 2023-01-10 19:20 UTC
Whenever you bring up an interface that pauses game time (i.e bank window, npc dialogue, etc.) the timer continues counting down. After closing the interface, the plugin then tries to add back the paused time. When doing so, it adds twice as much time as it should.

Step to Reproduce:
1) Pull out kitten, verify age and hunger (ex. 1:30:25 to full growth)
2) Open bank interface for set time (ex. 10 seconds)
3) Close interface and compare time left to that taken before bank (ex. Old - 1:30:25   New - 1:30:35)

**Comment by wetzel-cam** [comment] 2023-01-11 00:14
I believe this is the same issue as [this one](https://github.com/pieterjanbuntinx/kitten-tracker/issues/35), but this helps a lot!

**Comment by wetzel-cam** [comment] 2023-01-11 03:18
I believe [this commit](https://github.com/pieterjanbuntinx/kitten-tracker/blob/868708ce2e57d7c594a8cb38a7b99cd808579d78/src/main/java/com/kittentracker/KittenPlugin.java#L715-L729) is the cause of the behavior. Now, as for why this was added I'm not 100% sure. From my few tests of using the bank and dialogues (which the game counts as "Widgets") the timer still progresses. That snippet ends up adding time back unnecessarily after the interaction- is there a case where time gets paused? Possibly in cutscenes? Does that still count as time progressing in the background though?

@pieterjanbuntinx any thoughts?

**Comment by pieterjanbuntinx** [comment] 2023-01-11 14:48
When you have any dialog or widget open, all the timers of a kitten get paused. The kitten never gets hungry or never runs away. Or at least, it was like this when I did this commit.
Therefore I made the timers of the plugin "Pause" by adding some time constantly. Not the correct way, but I couldn't find how to do it the right way.

**Comment by wetzel-cam** [comment] 2023-01-11 23:45
Gotcha. I figured that was the case for it, but it seems like time just continues to tick down. I can't say it's 100% for every single dialog or widget, but the few common ones I've tested, it seems to not pause anymore. Thanks for the input.

**Comment by wetzel-cam** [comment] 2023-01-28 02:17
Addressed in PR#44

**Closed** 2023-01-28 02:16 UTC
Labels: bug
